name: rust-docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # TODO: Test here
  docker-push:
    runs-on: ubuntu-latest
    needs: build
    steps:  
    - uses: actions/checkout@v2
    - name: build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: dennybritz/papergraph
        tag_with_sha: true
        tag_with_ref: true
